In [1]:
import pandas as pd
from pathlib import Path

data_path = Path("/Users/rajubhattarai/Desktop/Global_Electronics_Analysis/data/raw")

In [2]:
customers = pd.read_csv(data_path/ "Customers.csv", encoding="latin1", keep_default_na=False, na_values=[""])
products = pd.read_csv(data_path/ "Products.csv")
sales = pd.read_csv(data_path/"Sales.csv")
stores = pd.read_csv(data_path/"Stores.csv")

In [3]:
print("Customers :", customers.shape)
print("Products : ", products.shape)
print("Sales : ", sales.shape)
print("Stores : ", stores.shape)

Customers : (15266, 10)
Products :  (2517, 10)
Sales :  (62884, 9)
Stores :  (67, 5)

In [4]:
customers.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15266 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

In [6]:
customers.isnull().sum()

CustomerKey    0
Gender         0
Name           0
City           0
State Code     0
State          0
Zip Code       0
Country        0
Continent      0
Birthday       0
dtype: int64

In [7]:
sales.duplicated().sum()

0

In [8]:
products.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [9]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB

In [10]:
products.isnull().sum()

ProductKey        0
Product Name      0
Brand             0
Color             0
Unit Cost USD     0
Unit Price USD    0
SubcategoryKey    0
Subcategory       0
CategoryKey       0
Category          0
dtype: int64

In [11]:
products.duplicated().sum()

0

In [12]:
sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [13]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

In [14]:
sales.isnull().sum()

Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64

In [15]:
sales.duplicated().sum()

0

In [16]:
stores.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

In [17]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB

In [18]:
stores.isnull().sum()

StoreKey         0
Country          0
State            0
Square Meters    1
Open Date        0
dtype: int64

In [19]:
df1 = stores
df1[df1['Square Meters'].isnull()]

    StoreKey Country   State  Square Meters Open Date
66         0  Online  Online            NaN  1/1/2010

In [20]:
stores.duplicated().sum()

0

In [21]:
customers['Birthday'] = pd.to_datetime(customers['Birthday'])

In [22]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15266 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 1.2+ MB

In [23]:
products['Unit Cost USD'] = (products['Unit Cost USD'].str.replace('$','', regex = False)
.str.replace(',','', regex= False).astype(float))

In [24]:
products['Unit Price USD'] = (products['Unit Price USD'].str.replace('$','', regex = False)
.str.replace(',','',regex = False).astype(float))

In [25]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   float64
 5   Unit Price USD  2517 non-null   float64
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 196.8+ KB

In [26]:
sales['Order Date'] = pd.to_datetime(sales['Order Date'])
sales['Delivery Date'] = pd.to_datetime(sales['Delivery Date'])

In [27]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  datetime64[ns]
 3   Delivery Date  13165 non-null  datetime64[ns]
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: datetime64[ns](2), int64(6), object(1)
memory usage: 4.3+ MB

In [28]:
stores['Open Date'] = pd.to_datetime(stores['Open Date'])

In [29]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 2.7+ KB

In [30]:
# Making all columns names to lower case removing space and changing space between to underscore 
def clean_column_names(df):
    df.columns = (df.columns.str.strip().str.lower().str.replace(" ","_"))
    return df

In [31]:
customers = clean_column_names(customers)
products = clean_column_names(products)
sales = clean_column_names(sales)
stores = clean_column_names(stores)

In [32]:
print(customers.columns.tolist())
print(products.columns.tolist())
print(sales.columns.tolist())
print(stores.columns.tolist())

['customerkey', 'gender', 'name', 'city', 'state_code', 'state', 'zip_code', 'country', 'continent', 'birthday']
['productkey', 'product_name', 'brand', 'color', 'unit_cost_usd', 'unit_price_usd', 'subcategorykey', 'subcategory', 'categorykey', 'category']
['order_number', 'line_item', 'order_date', 'delivery_date', 'customerkey', 'storekey', 'productkey', 'quantity', 'currency_code']
['storekey', 'country', 'state', 'square_meters', 'open_date']

In [33]:
# let change the name little more to look nice on some key things
customers = customers.rename(columns={
    "customerkey": "customer_key"
})

products = products.rename(columns={
    "productkey": "product_key",
    "subcategorykey": "subcategory_key",
    "categorykey": "category_key"
})

sales = sales.rename(columns = {
    "customerkey" : "customer_key",
    "storekey" : "store_key",
    "productkey" : "product_key"
})

stores = stores.rename(columns={
    "storekey": "store_key"
})

In [34]:
print(customers.columns.tolist())
print(products.columns.tolist())
print(sales.columns.tolist())
print(stores.columns.tolist())

['customer_key', 'gender', 'name', 'city', 'state_code', 'state', 'zip_code', 'country', 'continent', 'birthday']
['product_key', 'product_name', 'brand', 'color', 'unit_cost_usd', 'unit_price_usd', 'subcategory_key', 'subcategory', 'category_key', 'category']
['order_number', 'line_item', 'order_date', 'delivery_date', 'customer_key', 'store_key', 'product_key', 'quantity', 'currency_code']
['store_key', 'country', 'state', 'square_meters', 'open_date']

In [153]:
# Now exporting clean data
clean_path = "/Users/rajubhattarai/Desktop/Global_Electronics_Analysis/data/cleaned/ "

customers.to_csv(clean_path + "customers_clean.csv", index = False)
products.to_csv(clean_path + "products_clean.csv", index = False)
sales.to_csv(clean_path + "sales_clean.csv", index = False)
stores.to_csv(clean_path + "stores_clean.csv", index = False)